nome = str(input("Qual seu nome? "))
endereco = str(input("Qual seu endereço? "))
cidade = str(input("Qual a sua cidade? "))
cpf = int(input("Qual seu CPF? "))
rg = int(input("Qual seu RG? "))
idade = int(input("Qual sua idade? "))
nomeDoPai = str(input("Qual o nome do seu pai? "))
nomeDaMae = str(input("Qual o nome da sua mãe? "))
peso = float(input("Qual seu peso? "))
rendaBruta = float(input("Qual sua Renda Bruta? "))

print("---------------------------------------------------")
print("Respostas:")
print(" ")

print(f"Seu nome é: {nome}")
print(f"Seu endereço é: {endereco}")
print(f"Sua cidade é: {cidade}")
print(f"Seu CPF é: {str(cpf)}")
print(f"Seu RG é: {str(rg)}")
print(f"Sua idade é: {str(idade)}")
print(f"O nome da sua pai é: {nomeDoPai}")
print(f"O nome da sua mãe é: {nomeDaMae}")
print(f"O seu peso é: {str(peso)}")
print(f"Sua renda bruta é: {str(rendaBruta)}")
